[package]
name = "kms-v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yandex-cloud-api-core = {path = "../core"}

prost = "0.10.0"
prost-types = "0.10.0"
tonic = "0.7.1"